# ds_workflow_s2.py (为 Stage-2 优化的、简洁的版本)
from typing import Dict, Any, List, Optional
from langchain_core.messages import AIMessage, ToolMessage, SystemMessage, HumanMessage, BaseMessage
from langchain_core.prompts import ChatPromptTemplate
from langgraph.graph import StateGraph, END
import os
# 假设 prompts.py 和 common.py 在可导入的路径中
from core import prompts
from core.common import llm, AgentState, dbg, dbg_json
from core.metrics import note_tool_event, now_ms
import json

def _extract_text_content(msg: AIMessage) -> str:
    """把 AIMessage.content 轉成可讀字串：支援 str / list[dict] 兩種格式。"""
    c = getattr(msg, "content", "")
    if isinstance(c, str):
        return c
    if isinstance(c, list):
        parts = []
        for it in c:
            if isinstance(it, dict):
                # 常見型別：text / thought / explanation
                t = it.get("type")
                if t in ("text", "thought", "explanation"):
                    parts.append(it.get("text") or it.get("content") or "")
        return "\n".join(p for p in parts if p)
    # fallback
    return str(c)

def _last_human_snippet(state, n=300) -> str:
    for m in reversed(state.get("messages", [])):
        if isinstance(m, HumanMessage):
            return (m.content or "")[:n]
    return ""

# create_ds_executor 可以直接从旧文件复制，它足够通用
def create_ds_executor(mode: str, tools: List, system_prompt: Optional[str] = None):
    """
    ★★★ 兼容性修改 ★★★
    这个函数现在也接受 system_prompt 参数，使其与 DE 和 ME 保持一致。
    """

    final_sys_prompt_text = ""
    if system_prompt:
        # 如果 Stage-2 传入了新的 prompt (角色卡)，就使用它
        final_sys_prompt_text = system_prompt
    else:
        # 否则，保持 Stage-1 的旧逻辑
        # (这部分代码其实在 Stage-2 的流程中不会被触发，但保留它可以让这个函数更通用)
        tool_names = ", ".join([t.name for t in tools])
        prompt_template = prompts.DS_AUGMENTED_PROMPT if mode == "augmented" else prompts.DS_BASELINE_PROMPT
        final_sys_prompt_text = prompt_template.format(tool_names=tool_names)

    # 后续的绑定逻辑保持不变
    bound_llm = llm.bind_tools(tools)
    prompt = ChatPromptTemplate.from_messages([
        SystemMessage(content=final_sys_prompt_text),
        ("placeholder", "{messages}"),
    ])

    return prompt | bound_llm


# --- 通用节点 (直接从旧文件复制) ---
def ds_node(state: Dict[str, Any], executor):
    from core.llm_harness import SelfEvaluator
    print("\n[Node] >>> DataScientist")
    snippet = _last_human_snippet(state)
    print("[DS][In] last human: %r" % snippet)

    from core.harness_callback import HarnessCallback
    res = executor.invoke(state, config={"callbacks": [HarnessCallback(state, "DS")]})

    msgs: list[BaseMessage] = []
    if isinstance(res, dict) and "messages" in res:
        msgs = res["messages"] or []
    elif isinstance(res, BaseMessage):
        msgs = [res]
    else:
        print(f"[DS][DEBUG] unexpected executor result type: {type(res)} -> {res!r}")

    found_any = False
    last_ai_text = ""
    for msg in msgs:
        if isinstance(msg, AIMessage):
            found_any = True
            text = _extract_text_content(msg)
            last_ai_text = text or last_ai_text
            print(f"[DS][Thought] {text if text else '(empty)'}")
            tcs = getattr(msg, "tool_calls", None) or []
            if tcs:
                print("[DS][Plan tools] " + ", ".join(f"{tc.get('name')}({tc.get('args')})" for tc in tcs))
            else:
                print("[DS][Plan tools] (none)")
    if not found_any:
        print("[DS][DEBUG] no AIMessage found to print Thought")

    # SelfEvaluator（非阻塞）
    if last_ai_text:
        try:
            from core.common import llm as _llm
            SelfEvaluator().evaluate(_llm, last_ai_text, "DS", state)
        except Exception:
            pass

    return {"messages": msgs or ([res] if isinstance(res, BaseMessage) else [])}


def tool_node_ds(state: Dict[str, Any], tool_map: Dict[str, Any]):
    AGENT_TAG = "[DS]"
    print(f"\n[Node: DS] >>> ToolExecutor")

    last_message = state["messages"][-1]
    if not isinstance(last_message, AIMessage) or not last_message.tool_calls:
        return {}

    state.setdefault("tool_events", [])
    new_tool_messages: List[ToolMessage] = []

    for tool_call in last_message.tool_calls:
        name = tool_call.get("name")
        args = tool_call.get("args", {}) or {}
        call_id = tool_call.get("id", "tool_call_autogenerated")

        if name not in tool_map:
            print(f"{AGENT_TAG} [Tool] (skip) unknown tool: {name}")
            out_text = json.dumps({"status": "error", "error": f"Tool '{name}' not found."}, ensure_ascii=False)
            if "note_tool_event" in globals():
                note_tool_event(state, tool_name=name or "UNKNOWN", args=args,
                                started_ms=now_ms(), latency_ms=0, raw_output=out_text)
            new_tool_messages.append(ToolMessage(content=out_text, name=name, tool_call_id=call_id))
            continue

        fn = tool_map[name]
        print(f"{AGENT_TAG} [Tool] -> {name} args={repr(args)[:300]}")

        started = now_ms()
        try:
            raw = fn.invoke(args if isinstance(args, dict) else {})
        except Exception as e:
            raw = {"status": "error", "error": f"{type(e).__name__}: {e}"}
        latency = now_ms() - started

        # --- 正規化輸出 ---
        if isinstance(raw, (dict, list)):
            raw_obj = raw
            try:
                raw_text = json.dumps(raw, ensure_ascii=False)
            except Exception:
                raw_text = str(raw)
        elif isinstance(raw, (bytes, bytearray)):
            try:
                raw_text = raw.decode(errors="ignore")
            except Exception:
                raw_text = str(raw)
            try:
                raw_obj = json.loads(raw_text)
            except Exception:
                raw_obj = {}
        else:
            raw_text = str(raw)
            try:
                raw_obj = json.loads(raw_text)
            except Exception:
                raw_obj = {}

        head = (raw_text or "")[:1000].replace("\n", " ")
        print(f"{AGENT_TAG} [Tool] <- {name} {latency}ms head={head}")

        if "note_tool_event" in globals():
            note_tool_event(state, tool_name=name, args=args,
                            started_ms=started, latency_ms=latency, raw_output=raw_text)

        new_tool_messages.append(ToolMessage(content=raw_text, name=name, tool_call_id=call_id))

    return {"messages": new_tool_messages, "tool_events": state.get("tool_events", [])}


def router_ds(state: Dict[str, Any]):
    last_message = state["messages"][-1]
    if isinstance(last_message, AIMessage) and getattr(last_message, "tool_calls", None):
        return "ToolExecutor"
    return END


# ★★★ 核心修改：一个只为 Stage-2 服务的、简洁的 Graph 构建器 ★★★
def build_graph(agent_state_cls, ds_executor, tool_map, **kwargs):
    """
    构建并编译 DS 的工作流图。
    这个版本没有 InitNode，直接从 DataScientist 节点开始。
    """
    workflow = StateGraph(agent_state_cls)
    print(f"[DEBUG] RUN_ID={os.getenv('RUN_ID')}")
    workflow.add_node("DataScientist", lambda state: ds_node(state, executor=ds_executor))
    workflow.add_node("ToolExecutor", lambda state: tool_node_ds(state, tool_map=tool_map))

    # 入口点总是 DataScientist
    workflow.set_entry_point("DataScientist")

    workflow.add_edge("ToolExecutor", "DataScientist")

    workflow.add_conditional_edges(
        "DataScientist",
        router_ds,
        {"ToolExecutor": "ToolExecutor", END: END}
    )

    # 总是返回一个已编译的图

    return workflow.compile()
